
baseurl = "localhost:1313"
title = "Leanlang.com"
languageCode = "en-us"
theme = "hugo-elate-theme"



[params]
 # logo = "logo/leanlang.png"
  custom_css = ["css/custom1.css", "css/custom2.css"]
  favicon = "/favicon.ico"

  # Meta
  author = "Sara Senobari"
description = "Website for language courses and program management"
email = "info@leanlang.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

 # Navigation
[params.navigation]
  brand = "Leanlang.com"
  home = "Accueil"
  work = "Services"
  testimonials = "Témoignages"
  about = "À propos"
  contact = "Contact"


  [[menu.main]]
    identifier = "category1"
    name = "Category1"
    url = "/work/category1"
    parent = "work"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "work"
    url = "/work/category2"
    parent = "work"
    weight = 2

 # [params.navigation.services]
  #  enable = true
   # name = "Services"
    #submenu = [
     # { name = "Service 1", url = "#" },
      #{ name = "Service 2", url = "#" },
     # { name = "Service 3", url = "#" }
    #]

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

# Hero section
[params.hero]
title = "Cours d'anglais personnalisés et suivi de formation en ligne"
subtitle = "Apprenez l'anglais professionnel et réussissez vos examens de langues avec notre programme de formation destiné aux écoles privées et universités"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
title = "Méthodologie de travail avec empathie"
description = "Notre approche se base sur l'empathie envers nos clients. Nous comprenons leurs besoins spécifiques, leurs défis et leurs objectifs, et nous nous engageons à fournir des solutions personnalisées qui répondent à leurs attentes."
url = "mailto:info@leanlang.com"
button = "Nous contacter"
icon = "icon-bulb"
img = "img_7.jpg"


  [[params.intro.item]]
title = "Enseignement et Gestion Innovants"
description = "Chez nous, nous privilégions l'innovation dans l'enseignement et la gestion. Nous offrons des services aussi bien à distance qu'en présentiel pour répondre aux besoins de chacun. Notre objectif est de fournir un environnement d'apprentissage flexible, sans compromettre l'efficacité ni la qualité. Rejoignez-nous dans ce voyage passionnant pour redéfinir l'éducation et la gestion."
url = "mailto:info@leanlang.com"
button = "Cliquez ici"
icon = "icon-desktop"
img = "img_8.jpg"

[[params.intro.item]]
title = "Préparation aux Examens"
description = "Nous sommes spécialisés dans la préparation aux examens, avec une équipe d'examinateurs certifiés à votre disposition. Nous vous fournissons une préparation approfondie et ciblée pour vous assurer que vous êtes bien équipé pour réussir vos examens. Notre équipe expérimentée vous guide à travers le processus, en mettant l'accent sur les domaines clés et en fournissant des conseils stratégiques pour maximiser votre performance. Avec nous, vous pouvez avoir confiance dans votre préparation."
url = "mailto:info@leanlang.com"
button = "Pourquoi nous ?"
icon = "icon-flag"
img = "img_10.jpg"

  # [params.intro.video]
    # enable = true
   #  title = "Regardez la vidéo"
    # icon = "icon-play2"
    # url = "https://vimeo.com/channels/staffpicks/93951774"

  # Work section
  [params.work]
    enable = true
    title = "Services"
    description = "Nos services se concentrent sur l'enseignement des langues et la conception et gestion de programmes adaptés aux besoins des établissements scolaires privés et des universités. Nous travaillons en partenariat avec ces institutions pour offrir des solutions efficaces et personnalisées qui favorisent l'apprentissage des langues et le développement des programmes éducatifs."
    footertext = ' <a href="" target="_blank"></a>'

    [[params.work.row]]
      img = "projects/smile.jpg"
      alt = "Image2"
      title = "Evaluation et réparation aux examens de langues"
      subtitle = "Travail effectué pour un client, qui est une école de langues à Paris"
      link = "/examens/"  # Replace "path/to/custom.html" with the actual path to your custom HTML file

    [[params.work.row]]
    img = "projects/salle.jpg"
    alt = "Image2"
    title = "Rédaction et suivi des programmes pédagogiques"
    subtitle = "Anglais et français personnalisés pour écoles et universités"
    link = "/programmes/"

    [[params.work.row]]
    img = "projects/business.jpg"
alt = "Image3"
title = "Coaching et préparation de présentations"
subtitle = "Pour une communication professionnelle et des présentations percutantes"
    link = "/coaching/"


# Testimonials section
[params.testimonials]
enable = true
title = "Témoignages"
description = "Découvrez ce que nos clients disent à propos de nos services de cours d'anglais personnalisés et de suivi de formation en ligne."

    [[params.testimonials.item]]
      quote = "&ldquo;Grâce aux cours d'anglais de Leanlang.com, j'ai pu améliorer mes compétences linguistiques et ouvrir de nouvelles opportunités professionnelles.&rdquo;"
      person = 'François'
      img = "testimonals/F2.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Les formations d'anglais chez Leanlang.com m'ont permis de communiquer efficacement avec mes clients internationaux et d'élargir mes horizons professionnels.&rdquo;"
      person = 'Moussa'
      img = "testimonals/IMG_1314.JPG"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Je suis reconnaissante envers Leanlang.com pour m'avoir aidé à maîtriser l'anglais professionnel. Cela m'a permis de gravir les échelons dans mon entreprise.&rdquo;"
      person = 'Arnaud'
      img = "testimonals/arnaudmod.jpg"
      alt = "Person3"



  # Services section
  [params.services]
    enable = true
    title = "Services"
description = """
- Cours d'anglais et de français pour les étudiants et professionnels
- Préparation aux examens de langues
- Rédaction des programmes
- Coordination de la formation
"""

    [[params.services.item]]
title = "Cours de langue"
description = "Cours d'anglais et de français pour tous les niveaux. Méthodes pédagogiques efficaces."
icon = "icon-language"

[[params.services.item]]
title = "Rédaction de programmes d'enseignement d'anglais"
description = "Création de programmes d'anglais adaptés aux objectifs des écoles et gestion de la formation."
icon = "icon-square-check"

[[params.services.item]]
title = "Coaching personnel"
description = "Coaching personnalisé en anglais pour atteindre vos objectifs personnels et professionnels."
icon = "icon-comments"

[[params.services.item]]
title = "Préparation aux examens"
description = "Cours de préparation aux examens de langue avec conseils d'experts et ressources de qualité."
icon = "icon-flag-checkered"


  # About section
  [params.about]
  enable = true
   title = "À propos"
  description = "Nous sommes une équipe d'experts passionnés par l'enseignement des langues et le développement des programmes éducatifs. Notre objectif est de fournir une formation de haute qualité, adaptée aux besoins spécifiques de chaque institution, en combinant des approches pédagogiques innovantes, des ressources pédagogiques de qualité et un suivi personnalisé. Avec notre expertise et notre engagement envers l'excellence éducative, nous sommes votre partenaire de confiance dans l'amélioration de l'apprentissage des langues et le développement des programmes éducatifs."
  [[params.about.item]]
name = "Sara Senobari"
position = "Phd en didactique des langues diplômée de l’Université de Paris 3 Sorbonne Nouvelle"
description = "Spécialiste en didactique des langues, Sara est titulaire d'un doctorat de l'Université de Paris 3 Sorbonne Nouvelle. Elle possède une vaste expérience dans l'enseignement des langues et est passionnée par l'aide aux apprenants à atteindre leurs objectifs linguistiques. Avec son expertise académique et sa pédagogie innovante, elle est dédiée à fournir une formation de qualité et des résultats exceptionnels à ses étudiants."
img = "sphoto.jpg"
alt = "Sara"
social = [
  ["icon-twitter", "#lien-twitter"],
  # ["icon-facebook", "#lien-facebook"],
   #["icon-linkedin", "#lien-linkedin"]
]



 

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Etudiants diplomés"
      icon = "icon-briefcase"
      from = 0
      to = 769
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Heures enseignées"
      icon = "icon-clock"
      from = 0
      to = 7966
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Programmes créés"
      icon = "icon-book"
      from = 0
      to = 9
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Clients satisfaits"
      icon = "icon-people"
      from = 0
      to = 25
      interval = 50
      speed = 5000
# Contact section
[params.contact]
enable = true
map = true
form = true
title = "Contactez-nous"
description = "Pour les établissements scolaires et les demandes de services personnalisés, veuillez nous contacter."

    # Available icons: http://simplelineicons.com/
    details = [
      #    ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "0637076898"],
        ["icon-envelope", "info@leanlang.com"],
      ]

    #name = "Nom"
    email = "Email"
    #phone = "Téléphone"
    message = "Message"
    button = "Envoyer le message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Leanlang.com'
    links = [
        ["icon-twitter", "https://twitter.com/@leanlangdotcom"],
       #  ["icon-facebook", "#facebook"],
      #   ["icon-youtube", "#youtube"]
      ]
